from cashdata.domain.repositories.imonthly_income_repository import IMonthlyIncomeRepository
from cashdata.domain.repositories.iuser_repository import IUserRepository
from cashdata.domain.repositories.iunit_of_work import IUnitOfWork