"""remove due_date from installments

Revision ID: 3f64d359117e
Revises: 397ae91a41e4
Create Date: 2026-01-07 20:53:09.719792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f64d359117e'
down_revision: Union[str, Sequence[str], None] = '397ae91a41e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("installments", "due_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "installments",
        sa.Column("due_date", sa.Date(), nullable=False, server_default="2000-01-01"),
    )
    # ### end Alembic commands ###
